//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradebook.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallShedule
    {
        public CallShedule()
        {
            this.LessonShedules = new HashSet<LessonShedule>();
            this.Marks = new HashSet<Mark>();
        }
    
        public short Number { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
    
        public virtual ICollection<LessonShedule> LessonShedules { get; set; }
        public virtual ICollection<Mark> Marks { get; set; }
    }
}
