//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradebook.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public Grade()
        {
            this.Users = new HashSet<User>();
            this.LessonShedules = new HashSet<LessonShedule>();
        }
    
        public int Id { get; set; }
        public string GradeName { get; set; }
        public short BeginYear { get; set; }
        public short GraduateYear { get; set; }
        public int FormMasterId { get; set; }
        public bool Graduated { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<LessonShedule> LessonShedules { get; set; }
    }
}
