//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradebook.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public Grade()
        {
            this.LessonShedules = new HashSet<LessonShedule>();
            this.Pupils = new HashSet<Pupil>();
        }
    
        public int Id { get; set; }
        public string GradeName { get; set; }
        public short BeginYear { get; set; }
        public short GraduateYear { get; set; }
        public bool Graduated { get; set; }
    
        public virtual ICollection<LessonShedule> LessonShedules { get; set; }
        public virtual ICollection<Pupil> Pupils { get; set; }
        public virtual Teacher FormMaster { get; set; }
    }
}
