//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradebook.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LessonShedule
    {
        public int Id { get; set; }
        public int GradeId { get; set; }
        public short DayOfWeek { get; set; }
        public short LessonNumber { get; set; }
        public int SubjectId { get; set; }
        public int TeacherId { get; set; }
        public string ClassRoom { get; set; }
    
        public virtual CallShedule CallShedule { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual User User { get; set; }
    }
}
