//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradebook.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int Id { get; set; }
        public Nullable<short> Mark1 { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsPresent { get; set; }
    
        public virtual CallShedule CallShedule { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Pupil Pupil { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
