//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradebook.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pupil : User
    {
        public Pupil()
        {
            this.Marks = new HashSet<Mark>();
            this.Parents = new HashSet<Parent>();
        }
    
    
        public virtual ICollection<Mark> Marks { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual ICollection<Parent> Parents { get; set; }
    }
}
