//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradebook.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.LessonShedules = new HashSet<LessonShedule>();
            this.Marks = new HashSet<Mark>();
            this.Teachers = new HashSet<Teacher>();
        }
    
        public int Id { get; set; }
        public string SubjectName { get; set; }
    
        public virtual ICollection<LessonShedule> LessonShedules { get; set; }
        public virtual ICollection<Mark> Marks { get; set; }
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
