//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradebook.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Grades = new HashSet<Grade>();
            this.LessonShedules = new HashSet<LessonShedule>();
            this.Marks = new HashSet<Mark>();
            this.Marks1 = new HashSet<Mark>();
            this.ParentPupils = new HashSet<ParentPupil>();
            this.ParentPupils1 = new HashSet<ParentPupil>();
            this.User1 = new HashSet<User>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string ResidentalAdress { get; set; }
        public string RegisteredAdress { get; set; }
        public string Phone { get; set; }
        public string HomePhone { get; set; }
        public Nullable<int> GradeId { get; set; }
        public string JobTitle { get; set; }
        public string WorkTitle { get; set; }
        public string Relationship { get; set; }
        public bool Deleted { get; set; }
        public int Role { get; set; }
        public string UserType { get; set; }
    
        public virtual ICollection<Grade> Grades { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual ICollection<LessonShedule> LessonShedules { get; set; }
        public virtual ICollection<Mark> Marks { get; set; }
        public virtual ICollection<Mark> Marks1 { get; set; }
        public virtual ICollection<ParentPupil> ParentPupils { get; set; }
        public virtual ICollection<ParentPupil> ParentPupils1 { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
